apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200  # Port exposed by the Angular application inside the container
      nodePort: 31000   # Specify a NodePort within the valid range (30000-32767)
  type: NodePort

